const names = [
    "John",
    "William",
    "James",
    "Henry",
    "Robert",
    "Michael",
    "David",
    "Joseph",
    "Charles",
    "Thomas",
    "Daniel",
    "Matthew",
    "Anthony",
    "Donald",
    "Steven",
    "Paul",
    "Andrew",
    "Joshua",
    "Kenneth",
    "Kevin",
    "Brian",
    "George",
    "Edward",
    "Ronald",
    "Timothy",
    "Jason",
    "Jeffrey",
    "Ryan",
    "Jacob",
    "Gary",
    "Nicholas",
    "Eric",
    "Jonathan",
    "Stephen",
    "Larry",
    "Justin",
    "Scott",
    "Brandon",
    "Benjamin",
    "Samuel",
    "Frank",
    "Gregory",
    "Raymond",
    "Alexander",
    "Patrick",
    "Jack",
    "Dennis",
    "Jerry",
    "Tyler",
    "Aaron",
    "Jose",
    "Adam",
    "Henry",
    "Nathan",
    "Douglas",
    "Zachary",
    "Peter",
    "Kyle",
    "Walter",
    "Harold",
    "Jeremy",
    "Ethan",
    "Carl",
    "Keith",
    "Roger",
    "Gerald",
    "Christian",
    "Terry",
    "Sean",
    "Arthur",
    "Austin",
    "Noah",
    "Lawrence",
    "Jesse",
    "Joe",
    "Bryan",
    "Billy",
    "Jordan",
    "Albert",
    "Dylan",
    "Bruce",
    "Willie",
    "Gabriel",
    "Logan",
    "Alan",
    "Juan",
    "Wayne",
    "Ralph",
    "Roy",
    "Eugene",
    "Randy",
    "Vincent",
    "Russell",
    "Louis",
    "Philip",
    "Bobby",
    "Johnny"
  ];
  const thought = [
    "Life is a beautiful journey filled with endless possibilities.",
    "Embrace the present moment and let go of worries about the past and future.",
    "Learning is a lifelong adventure that enriches our minds and broadens our horizons.",
    "Nature has a way of soothing the soul and reminding us of life's simple joys.",
    "Unconditional love and companionship are the priceless gifts that dogs bring into our lives."
  ];
  const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

const getRandomName = () =>
  `${getRandomArrItem(names)} ${getRandomArrItem(names)}`;

const getRandomThought = () => `${getRandomArrItem(thought)}`;

module.exports = { getRandomName, getRandomThought };